[params]
  disableScale = true
    [params.preview]
        outputPrefix = "ogPreview-overlay"
        outputSuffix = ".png"
        format =  "svg"
        image = "web.png"
        source = "file"

        debug = true

        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
            removeMissing = true

        [params.footer]
            privacy = true

[params.author]
    email = 'mail@christianmahnke.de'
    name = 'Christian Mahnke'
    uri = 'http://www.wikidata.org/entity/Q137668638'
